/**
 * LanguageContext - Global language state management
 * Provides language selection and translation across the entire app
 */

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { languageService } from '../services';

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
  supportedLanguages: Array<{ code: string; name: string; nativeName: string }>;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState('en');

  // Initialize language from localStorage or user profile
  useEffect(() => {
    const storedLanguage = localStorage.getItem('appLanguage');
    const storedUser = localStorage.getItem('user');
    
    if (storedLanguage) {
      setCurrentLanguage(storedLanguage);
      languageService.initialize(storedLanguage);
    } else if (storedUser) {
      const userData = JSON.parse(storedUser);
      const userLanguage = userData.language?.toLowerCase() || 'en';
      setCurrentLanguage(userLanguage);
      languageService.initialize(userLanguage);
    }
  }, []);

  const setLanguage = (language: string) => {
    setCurrentLanguage(language);
    localStorage.setItem('appLanguage', language);
    languageService.setPreferredLanguage(language);
    console.log('Global language changed to:', language);
  };

  const t = (key: string): string => {
    return translations[currentLanguage]?.[key] || translations['en'][key] || key;
  };

  const supportedLanguages = languageService.getSupportedLanguages();

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, supportedLanguages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

// Translation dictionary
const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.how_it_works': 'How It Works',
    'nav.about': 'About',
    'nav.stories': 'Stories',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.profile': 'Profile',
    'nav.history': 'History',
    'nav.feedback': 'Feedback',
    'nav.support': 'Support',
    'nav.logout': 'Logout',
    
    // Hero Section
    'hero.title': 'Check Your Eligibility',
    'hero.subtitle': 'Use voice input in any language to quickly check which government schemes you\'re eligible for',
    'hero.cta': 'Check Eligibility Now',
    'hero.quick_easy': 'Quick & Easy',
    'hero.multilingual': 'Multilingual Voice Support',
    
    // Check Eligibility Page
    'eligibility.title': 'Check Your Eligibility',
    'eligibility.subtitle': 'Use voice input in any language to quickly check which government schemes you\'re eligible for',
    'eligibility.step1': 'Step 1: Use Voice Input',
    'eligibility.voice_instruction': 'Click the microphone and speak your details in any language. We\'ll automatically detect your language and fill the form.',
    'eligibility.input_fields': '(State, District, Land Size, Crop Type, Category, Annual Income, Income Tax Status, Pension Status, Electricity Connection)',
    'eligibility.start_recording': 'Click to Start Recording',
    'eligibility.stop_recording': 'Click to Stop Recording',
    'eligibility.processing': 'Processing your speech...',
    'eligibility.skip_manual': 'Skip & Fill Manually',
    'eligibility.step2': 'Step 2: Review & Edit Details',
    'eligibility.use_voice': 'Use Voice Input',
    'eligibility.check_btn': 'Check Eligibility',
    'eligibility.checking': 'Checking Eligibility...',
    
    // Form Fields
    'form.state': 'State',
    'form.district': 'District',
    'form.land_size': 'Land Size (acres)',
    'form.crop_type': 'Crop Type',
    'form.category': 'Category',
    'form.annual_income': 'Annual Income (₹)',
    'form.income_tax_payer': 'Income Tax Payer',
    'form.pension': 'Receiving Pension',
    'form.pension_amount': 'Monthly Pension Amount (₹)',
    'form.electricity': 'Electricity Connection',
    'form.select': 'Select',
    'form.select_state': 'Select State',
    'form.select_district': 'Select District',
    'form.select_category': 'Select Category',
    'form.yes': 'Yes',
    'form.no': 'No',
    'form.required': 'Required',
    
    // Results
    'results.recommended': 'Recommended Scheme',
    'results.best_match': 'Best match for your profile',
    'results.eligible': 'Eligible',
    'results.not_eligible': 'Not Eligible',
    'results.total_schemes': 'Total Eligible Schemes',
    'results.eligible_schemes': 'Eligible Schemes',
    'results.check_another': 'Check Another Eligibility',
    
    // Common
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.features': 'विशेषताएं',
    'nav.how_it_works': 'यह कैसे काम करता है',
    'nav.about': 'के बारे में',
    'nav.stories': 'कहानियां',
    'nav.faq': 'सामान्य प्रश्न',
    'nav.contact': 'संपर्क करें',
    'nav.login': 'लॉगिन',
    'nav.register': 'रजिस्टर',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.history': 'इतिहास',
    'nav.feedback': 'प्रतिक्रिया',
    'nav.support': 'सहायता',
    'nav.logout': 'लॉगआउट',
    
    // Hero Section
    'hero.title': 'अपनी पात्रता जांचें',
    'hero.subtitle': 'किसी भी भाषा में वॉयस इनपुट का उपयोग करके जल्दी से जांचें कि आप किन सरकारी योजनाओं के लिए पात्र हैं',
    'hero.cta': 'अभी पात्रता जांचें',
    'hero.quick_easy': 'त्वरित और आसान',
    'hero.multilingual': 'बहुभाषी वॉयस सपोर्ट',
    
    // Check Eligibility Page
    'eligibility.title': 'अपनी पात्रता जांचें',
    'eligibility.subtitle': 'किसी भी भाषा में वॉयस इनपुट का उपयोग करके जल्दी से जांचें कि आप किन सरकारी योजनाओं के लिए पात्र हैं',
    'eligibility.step1': 'चरण 1: वॉयस इनपुट का उपयोग करें',
    'eligibility.voice_instruction': 'माइक्रोफ़ोन पर क्लिक करें और किसी भी भाषा में अपना विवरण बोलें। हम स्वचालित रूप से आपकी भाषा का पता लगाएंगे और फॉर्म भर देंगे।',
    'eligibility.input_fields': '(राज्य, जिला, भूमि का आकार, फसल का प्रकार, श्रेणी, वार्षिक आय, आयकर स्थिति, पेंशन स्थिति, बिजली कनेक्शन)',
    'eligibility.start_recording': 'रिकॉर्डिंग शुरू करने के लिए क्लिक करें',
    'eligibility.stop_recording': 'रिकॉर्डिंग बंद करने के लिए क्लिक करें',
    'eligibility.processing': 'आपके भाषण को संसाधित कर रहे हैं...',
    'eligibility.skip_manual': 'छोड़ें और मैन्युअल रूप से भरें',
    'eligibility.step2': 'चरण 2: विवरण की समीक्षा और संपादन करें',
    'eligibility.use_voice': 'वॉयस इनपुट का उपयोग करें',
    'eligibility.check_btn': 'पात्रता जांचें',
    'eligibility.checking': 'पात्रता जांच रहे हैं...',
    
    // Form Fields
    'form.state': 'राज्य',
    'form.district': 'जिला',
    'form.land_size': 'भूमि का आकार (एकड़)',
    'form.crop_type': 'फसल का प्रकार',
    'form.category': 'श्रेणी',
    'form.annual_income': 'वार्षिक आय (₹)',
    'form.income_tax_payer': 'आयकर दाता',
    'form.pension': 'पेंशन प्राप्त कर रहे हैं',
    'form.pension_amount': 'मासिक पेंशन राशि (₹)',
    'form.electricity': 'बिजली कनेक्शन',
    'form.select': 'चुनें',
    'form.select_state': 'राज्य चुनें',
    'form.select_district': 'जिला चुनें',
    'form.select_category': 'श्रेणी चुनें',
    'form.yes': 'हाँ',
    'form.no': 'नहीं',
    'form.required': 'आवश्यक',
    
    // Results
    'results.recommended': 'अनुशंसित योजना',
    'results.best_match': 'आपकी प्रोफ़ाइल के लिए सर्वोत्तम मिलान',
    'results.eligible': 'पात्र',
    'results.not_eligible': 'अपात्र',
    'results.total_schemes': 'कुल पात्र योजनाएं',
    'results.eligible_schemes': 'पात्र योजनाएं',
    'results.check_another': 'दूसरी पात्रता जांचें',
    
    // Common
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.submit': 'जमा करें',
    'common.cancel': 'रद्द करें',
    'common.save': 'सहेजें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.close': 'बंद करें',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
  },
  te: {
    // Navigation
    'nav.home': 'హోమ్',
    'nav.features': 'ఫీచర్లు',
    'nav.how_it_works': 'ఇది ఎలా పనిచేస్తుంది',
    'nav.about': 'గురించి',
    'nav.stories': 'కథలు',
    'nav.faq': 'తరచుగా అడిగే ప్రశ్నలు',
    'nav.contact': 'సంప్రదించండి',
    'nav.login': 'లాగిన్',
    'nav.register': 'రిజిస్టర్',
    'nav.profile': 'ప్రొఫైల్',
    'nav.history': 'చరిత్ర',
    'nav.feedback': 'అభిప్రాయం',
    'nav.support': 'మద్దతు',
    'nav.logout': 'లాగౌట్',
    
    // Hero Section
    'hero.title': 'మీ అర్హతను తనిఖీ చేయండి',
    'hero.subtitle': 'మీరు ఏ ప్రభుత్వ పథకాలకు అర్హులో త్వరగా తనిఖీ చేయడానికి ఏ భాషలోనైనా వాయిస్ ఇన్‌పుట్ ఉపయోగించండి',
    'hero.cta': 'ఇప్పుడే అర్హతను తనిఖీ చేయండి',
    'hero.quick_easy': 'త్వరగా & సులభంగా',
    'hero.multilingual': 'బహుభాషా వాయిస్ మద్దతు',
    
    // Check Eligibility Page
    'eligibility.title': 'మీ అర్హతను తనిఖీ చేయండి',
    'eligibility.subtitle': 'మీరు ఏ ప్రభుత్వ పథకాలకు అర్హులో త్వరగా తనిఖీ చేయడానికి ఏ భాషలోనైనా వాయిస్ ఇన్‌పుట్ ఉపయోగించండి',
    'eligibility.step1': 'దశ 1: వాయిస్ ఇన్‌పుట్ ఉపయోగించండి',
    'eligibility.voice_instruction': 'మైక్రోఫోన్‌ను క్లిక్ చేసి ఏ భాషలోనైనా మీ వివరాలను మాట్లాడండి. మేము స్వయంచాలకంగా మీ భాషను గుర్తించి ఫారమ్‌ను పూరిస్తాము.',
    'eligibility.input_fields': '(రాష్ట్రం, జిల్లా, భూమి పరిమాణం, పంట రకం, వర్గం, వార్షిక ఆదాయం, ఆదాయపు పన్ను స్థితి, పెన్షన్ స్థితి, విద్యుత్ కనెక్షన్)',
    'eligibility.start_recording': 'రికార్డింగ్ ప్రారంభించడానికి క్లిక్ చేయండి',
    'eligibility.stop_recording': 'రికార్డింగ్ ఆపడానికి క్లిక్ చేయండి',
    'eligibility.processing': 'మీ ప్రసంగాన్ని ప్రాసెస్ చేస్తోంది...',
    'eligibility.skip_manual': 'దాటవేసి మాన్యువల్‌గా పూరించండి',
    'eligibility.step2': 'దశ 2: వివరాలను సమీక్షించండి & సవరించండి',
    'eligibility.use_voice': 'వాయిస్ ఇన్‌పుట్ ఉపయోగించండి',
    'eligibility.check_btn': 'అర్హతను తనిఖీ చేయండి',
    'eligibility.checking': 'అర్హతను తనిఖీ చేస్తోంది...',
    
    // Form Fields
    'form.state': 'రాష్ట్రం',
    'form.district': 'జిల్లా',
    'form.land_size': 'భూమి పరిమాణం (ఎకరాలు)',
    'form.crop_type': 'పంట రకం',
    'form.category': 'వర్గం',
    'form.annual_income': 'వార్షిక ఆదాయం (₹)',
    'form.income_tax_payer': 'ఆదాయపు పన్ను చెల్లింపుదారు',
    'form.pension': 'పెన్షన్ పొందుతున్నారు',
    'form.pension_amount': 'నెలవారీ పెన్షన్ మొత్తం (₹)',
    'form.electricity': 'విద్యుత్ కనెక్షన్',
    'form.select': 'ఎంచుకోండి',
    'form.select_state': 'రాష్ట్రాన్ని ఎంచుకోండి',
    'form.select_district': 'జిల్లాను ఎంచుకోండి',
    'form.select_category': 'వర్గాన్ని ఎంచుకోండి',
    'form.yes': 'అవును',
    'form.no': 'కాదు',
    'form.required': 'అవసరం',
    
    // Results
    'results.recommended': 'సిఫార్సు చేయబడిన పథకం',
    'results.best_match': 'మీ ప్రొఫైల్‌కు ఉత్తమ సరిపోలిక',
    'results.eligible': 'అర్హత',
    'results.not_eligible': 'అర్హత లేదు',
    'results.total_schemes': 'మొత్తం అర్హ పథకాలు',
    'results.eligible_schemes': 'అర్హ పథకాలు',
    'results.check_another': 'మరొక అర్హతను తనిఖీ చేయండి',
    
    // Common
    'common.back': 'వెనుకకు',
    'common.next': 'తదుపరి',
    'common.submit': 'సమర్పించండి',
    'common.cancel': 'రద్దు చేయండి',
    'common.save': 'సేవ్ చేయండి',
    'common.edit': 'సవరించండి',
    'common.delete': 'తొలగించండి',
    'common.close': 'మూసివేయండి',
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.error': 'లోపం',
    'common.success': 'విజయం',
  },
  ta: {
    'nav.home': 'முகப்பு',
    'nav.features': 'அம்சங்கள்',
    'nav.how_it_works': 'இது எவ்வாறு செயல்படுகிறது',
    'nav.about': 'பற்றி',
    'nav.stories': 'கதைகள்',
    'nav.faq': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    'nav.contact': 'தொடர்பு',
    'nav.login': 'உள்நுழைய',
    'nav.register': 'பதிவு',
    'nav.profile': 'சுயவிவரம்',
    'nav.history': 'வரலாறு',
    'nav.feedback': 'கருத்து',
    'nav.support': 'ஆதரவு',
    'nav.logout': 'வெளியேறு',
    'hero.title': 'உங்கள் தகுதியை சரிபார்க்கவும்',
    'hero.subtitle': 'எந்த மொழியிலும் குரல் உள்ளீட்டைப் பயன்படுத்தி நீங்கள் எந்த அரசு திட்டங்களுக்கு தகுதியானவர் என்பதை விரைவாக சரிபார்க்கவும்',
    'hero.cta': 'இப்போது தகுதியை சரிபார்க்கவும்',
    'hero.quick_easy': 'விரைவான & எளிதான',
    'hero.multilingual': 'பல்மொழி குரல் ஆதரவு',
    'eligibility.title': 'உங்கள் தகுதியை சரிபார்க்கவும்',
    'eligibility.subtitle': 'எந்த மொழியிலும் குரல் உள்ளீட்டைப் பயன்படுத்தி நீங்கள் எந்த அரசு திட்டங்களுக்கு தகுதியானவர் என்பதை விரைவாக சரிபார்க்கவும்',
    'eligibility.step1': 'படி 1: குரல் உள்ளீட்டைப் பயன்படுத்தவும்',
    'eligibility.voice_instruction': 'மைக்ரோஃபோனைக் கிளிக் செய்து எந்த மொழியிலும் உங்கள் விவரங்களைப் பேசுங்கள். நாங்கள் தானாகவே உங்கள் மொழியைக் கண்டறிந்து படிவத்தை நிரப்புவோம்.',
    'eligibility.input_fields': '(மாநிலம், மாவட்டம், நில அளவு, பயிர் வகை, வகை, ஆண்டு வருமானம், வருமான வரி நிலை, ஓய்வூதிய நிலை, மின்சார இணைப்பு)',
    'eligibility.start_recording': 'பதிவைத் தொடங்க கிளிக் செய்யவும்',
    'eligibility.stop_recording': 'பதிவை நிறுத்த கிளிக் செய்யவும்',
    'eligibility.processing': 'உங்கள் பேச்சை செயலாக்குகிறது...',
    'eligibility.skip_manual': 'தவிர்த்து கைமுறையாக நிரப்பவும்',
    'eligibility.step2': 'படி 2: விவரங்களை மதிப்பாய்வு செய்து திருத்தவும்',
    'eligibility.use_voice': 'குரல் உள்ளீட்டைப் பயன்படுத்தவும்',
    'eligibility.check_btn': 'தகுதியை சரிபார்க்கவும்',
    'eligibility.checking': 'தகுதியை சரிபார்க்கிறது...',
    'form.state': 'மாநிலம்',
    'form.district': 'மாவட்டம்',
    'form.land_size': 'நில அளவு (ஏக்கர்)',
    'form.crop_type': 'பயிர் வகை',
    'form.category': 'வகை',
    'form.annual_income': 'ஆண்டு வருமானம் (₹)',
    'form.income_tax_payer': 'வருமான வரி செலுத்துபவர்',
    'form.pension': 'ஓய்வூதியம் பெறுதல்',
    'form.pension_amount': 'மாதாந்திர ஓய்வூதிய தொகை (₹)',
    'form.electricity': 'மின்சார இணைப்பு',
    'form.select': 'தேர்ந்தெடுக்கவும்',
    'form.select_state': 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
    'form.select_district': 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
    'form.select_category': 'வகையைத் தேர்ந்தெடுக்கவும்',
    'form.yes': 'ஆம்',
    'form.no': 'இல்லை',
    'form.required': 'தேவை',
    'results.recommended': 'பரிந்துரைக்கப்பட்ட திட்டம்',
    'results.best_match': 'உங்கள் சுயவிவரத்திற்கு சிறந்த பொருத்தம்',
    'results.eligible': 'தகுதியானது',
    'results.not_eligible': 'தகுதியற்றது',
    'results.total_schemes': 'மொத்த தகுதியான திட்டங்கள்',
    'results.eligible_schemes': 'தகுதியான திட்டங்கள்',
    'results.check_another': 'மற்றொரு தகுதியை சரிபார்க்கவும்',
    'common.back': 'பின்',
    'common.next': 'அடுத்து',
    'common.submit': 'சமர்ப்பிக்கவும்',
    'common.cancel': 'ரத்து செய்',
    'common.save': 'சேமி',
    'common.edit': 'திருத்து',
    'common.delete': 'நீக்கு',
    'common.close': 'மூடு',
    'common.loading': 'ஏற்றுகிறது...',
    'common.error': 'பிழை',
    'common.success': 'வெற்றி',
  },
  kn: {
    'nav.home': 'ಮುಖಪುಟ',
    'nav.features': 'ವೈಶಿಷ್ಟ್ಯಗಳು',
    'nav.how_it_works': 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    'nav.about': 'ಬಗ್ಗೆ',
    'nav.stories': 'ಕಥೆಗಳು',
    'nav.faq': 'ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು',
    'nav.contact': 'ಸಂಪರ್ಕಿಸಿ',
    'nav.login': 'ಲಾಗಿನ್',
    'nav.register': 'ನೋಂದಣಿ',
    'nav.profile': 'ಪ್ರೊಫೈಲ್',
    'nav.history': 'ಇತಿಹಾಸ',
    'nav.feedback': 'ಪ್ರತಿಕ್ರಿಯೆ',
    'nav.support': 'ಬೆಂಬಲ',
    'nav.logout': 'ಲಾಗ್ಔಟ್',
    'hero.title': 'ನಿಮ್ಮ ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ',
    'hero.subtitle': 'ಯಾವುದೇ ಭಾಷೆಯಲ್ಲಿ ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಬಳಸಿ ನೀವು ಯಾವ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳಿಗೆ ಅರ್ಹರು ಎಂಬುದನ್ನು ತ್ವರಿತವಾಗಿ ಪರಿಶೀಲಿಸಿ',
    'hero.cta': 'ಈಗ ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ',
    'hero.quick_easy': 'ತ್ವರಿತ ಮತ್ತು ಸುಲಭ',
    'hero.multilingual': 'ಬಹುಭಾಷಾ ಧ್ವನಿ ಬೆಂಬಲ',
    'eligibility.title': 'ನಿಮ್ಮ ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ',
    'eligibility.subtitle': 'ಯಾವುದೇ ಭಾಷೆಯಲ್ಲಿ ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಬಳಸಿ ನೀವು ಯಾವ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳಿಗೆ ಅರ್ಹರು ಎಂಬುದನ್ನು ತ್ವರಿತವಾಗಿ ಪರಿಶೀಲಿಸಿ',
    'eligibility.step1': 'ಹಂತ 1: ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಬಳಸಿ',
    'eligibility.voice_instruction': 'ಮೈಕ್ರೊಫೋನ್ ಕ್ಲಿಕ್ ಮಾಡಿ ಮತ್ತು ಯಾವುದೇ ಭಾಷೆಯಲ್ಲಿ ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಹೇಳಿ. ನಾವು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಪತ್ತೆ ಮಾಡುತ್ತೇವೆ ಮತ್ತು ಫಾರ್ಮ್ ಅನ್ನು ಭರ್ತಿ ಮಾಡುತ್ತೇವೆ.',
    'eligibility.input_fields': '(ರಾಜ್ಯ, ಜಿಲ್ಲೆ, ಭೂಮಿ ಗಾತ್ರ, ಬೆಳೆ ಪ್ರಕಾರ, ವರ್ಗ, ವಾರ್ಷಿಕ ಆದಾಯ, ಆದಾಯ ತೆರಿಗೆ ಸ್ಥಿತಿ, ಪಿಂಚಣಿ ಸ್ಥಿತಿ, ವಿದ್ಯುತ್ ಸಂಪರ್ಕ)',
    'eligibility.start_recording': 'ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    'eligibility.stop_recording': 'ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    'eligibility.processing': 'ನಿಮ್ಮ ಭಾಷಣವನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...',
    'eligibility.skip_manual': 'ಬಿಟ್ಟು ಹಸ್ತಚಾಲಿತವಾಗಿ ಭರ್ತಿ ಮಾಡಿ',
    'eligibility.step2': 'ಹಂತ 2: ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸಂಪಾದಿಸಿ',
    'eligibility.use_voice': 'ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಬಳಸಿ',
    'eligibility.check_btn': 'ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ',
    'eligibility.checking': 'ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    'form.state': 'ರಾಜ್ಯ',
    'form.district': 'ಜಿಲ್ಲೆ',
    'form.land_size': 'ಭೂಮಿ ಗಾತ್ರ (ಎಕರೆಗಳು)',
    'form.crop_type': 'ಬೆಳೆ ಪ್ರಕಾರ',
    'form.category': 'ವರ್ಗ',
    'form.annual_income': 'ವಾರ್ಷಿಕ ಆದಾಯ (₹)',
    'form.income_tax_payer': 'ಆದಾಯ ತೆರಿಗೆ ಪಾವತಿದಾರ',
    'form.pension': 'ಪಿಂಚಣಿ ಪಡೆಯುತ್ತಿದ್ದಾರೆ',
    'form.pension_amount': 'ಮಾಸಿಕ ಪಿಂಚಣಿ ಮೊತ್ತ (₹)',
    'form.electricity': 'ವಿದ್ಯುತ್ ಸಂಪರ್ಕ',
    'form.select': 'ಆಯ್ಕೆಮಾಡಿ',
    'form.select_state': 'ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'form.select_district': 'ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'form.select_category': 'ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'form.yes': 'ಹೌದು',
    'form.no': 'ಇಲ್ಲ',
    'form.required': 'ಅಗತ್ಯವಿದೆ',
    'results.recommended': 'ಶಿಫಾರಸು ಮಾಡಲಾದ ಯೋಜನೆ',
    'results.best_match': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ಗೆ ಉತ್ತಮ ಹೊಂದಾಣಿಕೆ',
    'results.eligible': 'ಅರ್ಹ',
    'results.not_eligible': 'ಅರ್ಹವಲ್ಲ',
    'results.total_schemes': 'ಒಟ್ಟು ಅರ್ಹ ಯೋಜನೆಗಳು',
    'results.eligible_schemes': 'ಅರ್ಹ ಯೋಜನೆಗಳು',
    'results.check_another': 'ಮತ್ತೊಂದು ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ',
    'common.back': 'ಹಿಂದೆ',
    'common.next': 'ಮುಂದೆ',
    'common.submit': 'ಸಲ್ಲಿಸಿ',
    'common.cancel': 'ರದ್ದುಮಾಡಿ',
    'common.save': 'ಉಳಿಸಿ',
    'common.edit': 'ಸಂಪಾದಿಸಿ',
    'common.delete': 'ಅಳಿಸಿ',
    'common.close': 'ಮುಚ್ಚಿ',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'common.error': 'ದೋಷ',
    'common.success': 'ಯಶಸ್ಸು',
  },
  ml: {
    'nav.home': 'ഹോം',
    'nav.features': 'സവിശേഷതകൾ',
    'nav.how_it_works': 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    'nav.about': 'കുറിച്ച്',
    'nav.stories': 'കഥകൾ',
    'nav.faq': 'പതിവായി ചോദിക്കുന്ന ചോദ്യങ്ങൾ',
    'nav.contact': 'ബന്ധപ്പെടുക',
    'nav.login': 'ലോഗിൻ',
    'nav.register': 'രജിസ്റ്റർ',
    'nav.profile': 'പ്രൊഫൈൽ',
    'nav.history': 'ചരിത്രം',
    'nav.feedback': 'പ്രതികരണം',
    'nav.support': 'പിന്തുണ',
    'nav.logout': 'ലോഗൗട്ട്',
    'hero.title': 'നിങ്ങളുടെ യോഗ്യത പരിശോധിക്കുക',
    'hero.subtitle': 'ഏത് ഭാഷയിലും വോയ്‌സ് ഇൻപുട്ട് ഉപയോഗിച്ച് നിങ്ങൾ ഏത് സർക്കാർ പദ്ധതികൾക്ക് യോഗ്യരാണെന്ന് വേഗത്തിൽ പരിശോധിക്കുക',
    'hero.cta': 'ഇപ്പോൾ യോഗ്യത പരിശോധിക്കുക',
    'hero.quick_easy': 'വേഗമേറിയതും എളുപ്പവും',
    'hero.multilingual': 'ബഹുഭാഷാ വോയ്‌സ് പിന്തുണ',
    'eligibility.title': 'നിങ്ങളുടെ യോഗ്യത പരിശോധിക്കുക',
    'eligibility.subtitle': 'ഏത് ഭാഷയിലും വോയ്‌സ് ഇൻപുട്ട് ഉപയോഗിച്ച് നിങ്ങൾ ഏത് സർക്കാർ പദ്ധതികൾക്ക് യോഗ്യരാണെന്ന് വേഗത്തിൽ പരിശോധിക്കുക',
    'eligibility.step1': 'ഘട്ടം 1: വോയ്‌സ് ഇൻപുട്ട് ഉപയോഗിക്കുക',
    'eligibility.voice_instruction': 'മൈക്രോഫോൺ ക്ലിക്ക് ചെയ്ത് ഏത് ഭാഷയിലും നിങ്ങളുടെ വിശദാംശങ്ങൾ പറയുക. ഞങ്ങൾ സ്വയമേവ നിങ്ങളുടെ ഭാഷ കണ്ടെത്തുകയും ഫോം പൂരിപ്പിക്കുകയും ചെയ്യും.',
    'eligibility.input_fields': '(സംസ്ഥാനം, ജില്ല, ഭൂമിയുടെ വലുപ്പം, വിള തരം, വിഭാഗം, വാർഷിക വരുമാനം, ആദായനികുതി നില, പെൻഷൻ നില, വൈദ്യുതി കണക്ഷൻ)',
    'eligibility.start_recording': 'റെക്കോർഡിംഗ് ആരംഭിക്കാൻ ക്ലിക്ക് ചെയ്യുക',
    'eligibility.stop_recording': 'റെക്കോർഡിംഗ് നിർത്താൻ ക്ലിക്ക് ചെയ്യുക',
    'eligibility.processing': 'നിങ്ങളുടെ സംസാരം പ്രോസസ്സ് ചെയ്യുന്നു...',
    'eligibility.skip_manual': 'ഒഴിവാക്കി സ്വമേധയാ പൂരിപ്പിക്കുക',
    'eligibility.step2': 'ഘട്ടം 2: വിശദാംശങ്ങൾ അവലോകനം ചെയ്ത് എഡിറ്റ് ചെയ്യുക',
    'eligibility.use_voice': 'വോയ്‌സ് ഇൻപുട്ട് ഉപയോഗിക്കുക',
    'eligibility.check_btn': 'യോഗ്യത പരിശോധിക്കുക',
    'eligibility.checking': 'യോഗ്യത പരിശോധിക്കുന്നു...',
    'form.state': 'സംസ്ഥാനം',
    'form.district': 'ജില്ല',
    'form.land_size': 'ഭൂമിയുടെ വലുപ്പം (ഏക്കർ)',
    'form.crop_type': 'വിള തരം',
    'form.category': 'വിഭാഗം',
    'form.annual_income': 'വാർഷിക വരുമാനം (₹)',
    'form.income_tax_payer': 'ആദായനികുതി അടയ്ക്കുന്നയാൾ',
    'form.pension': 'പെൻഷൻ ലഭിക്കുന്നു',
    'form.pension_amount': 'പ്രതിമാസ പെൻഷൻ തുക (₹)',
    'form.electricity': 'വൈദ്യുതി കണക്ഷൻ',
    'form.select': 'തിരഞ്ഞെടുക്കുക',
    'form.select_state': 'സംസ്ഥാനം തിരഞ്ഞെടുക്കുക',
    'form.select_district': 'ജില്ല തിരഞ്ഞെടുക്കുക',
    'form.select_category': 'വിഭാഗം തിരഞ്ഞെടുക്കുക',
    'form.yes': 'അതെ',
    'form.no': 'ഇല്ല',
    'form.required': 'ആവശ്യമാണ്',
    'results.recommended': 'ശുപാർശ ചെയ്ത പദ്ധതി',
    'results.best_match': 'നിങ്ങളുടെ പ്രൊഫൈലിന് മികച്ച പൊരുത്തം',
    'results.eligible': 'യോഗ്യത',
    'results.not_eligible': 'യോഗ്യതയില്ല',
    'results.total_schemes': 'മൊത്തം യോഗ്യമായ പദ്ധതികൾ',
    'results.eligible_schemes': 'യോഗ്യമായ പദ്ധതികൾ',
    'results.check_another': 'മറ്റൊരു യോഗ്യത പരിശോധിക്കുക',
    'common.back': 'പിന്നോട്ട്',
    'common.next': 'അടുത്തത്',
    'common.submit': 'സമർപ്പിക്കുക',
    'common.cancel': 'റദ്ദാക്കുക',
    'common.save': 'സംരക്ഷിക്കുക',
    'common.edit': 'എഡിറ്റ് ചെയ്യുക',
    'common.delete': 'ഇല്ലാതാക്കുക',
    'common.close': 'അടയ്ക്കുക',
    'common.loading': 'ലോഡ് ചെയ്യുന്നു...',
    'common.error': 'പിശക്',
    'common.success': 'വിജയം',
  },
  bn: {
    'nav.home': 'হোম',
    'nav.features': 'বৈশিষ্ট্য',
    'nav.how_it_works': 'এটি কীভাবে কাজ করে',
    'nav.about': 'সম্পর্কে',
    'nav.stories': 'গল্প',
    'nav.faq': 'প্রায়শই জিজ্ঞাসিত প্রশ্ন',
    'nav.contact': 'যোগাযোগ',
    'nav.login': 'লগইন',
    'nav.register': 'নিবন্ধন',
    'nav.profile': 'প্রোফাইল',
    'nav.history': 'ইতিহাস',
    'nav.feedback': 'প্রতিক্রিয়া',
    'nav.support': 'সহায়তা',
    'nav.logout': 'লগআউট',
    'hero.title': 'আপনার যোগ্যতা পরীক্ষা করুন',
    'hero.subtitle': 'যেকোনো ভাষায় ভয়েস ইনপুট ব্যবহার করে দ্রুত পরীক্ষা করুন আপনি কোন সরকারি প্রকল্পের জন্য যোগ্য',
    'hero.cta': 'এখনই যোগ্যতা পরীক্ষা করুন',
    'hero.quick_easy': 'দ্রুত এবং সহজ',
    'hero.multilingual': 'বহুভাষিক ভয়েস সমর্থন',
    'eligibility.title': 'আপনার যোগ্যতা পরীক্ষা করুন',
    'eligibility.subtitle': 'যেকোনো ভাষায় ভয়েস ইনপুট ব্যবহার করে দ্রুত পরীক্ষা করুন আপনি কোন সরকারি প্রকল্পের জন্য যোগ্য',
    'eligibility.step1': 'ধাপ ১: ভয়েস ইনপুট ব্যবহার করুন',
    'eligibility.voice_instruction': 'মাইক্রোফোনে ক্লিক করুন এবং যেকোনো ভাষায় আপনার বিবরণ বলুন। আমরা স্বয়ংক্রিয়ভাবে আপনার ভাষা সনাক্ত করব এবং ফর্ম পূরণ করব।',
    'eligibility.input_fields': '(রাজ্য, জেলা, জমির আকার, ফসলের ধরন, শ্রেণী, বার্ষিক আয়, আয়কর অবস্থা, পেনশন অবস্থা, বিদ্যুৎ সংযোগ)',
    'eligibility.start_recording': 'রেকর্ডিং শুরু করতে ক্লিক করুন',
    'eligibility.stop_recording': 'রেকর্ডিং বন্ধ করতে ক্লিক করুন',
    'eligibility.processing': 'আপনার বক্তৃতা প্রক্রিয়া করা হচ্ছে...',
    'eligibility.skip_manual': 'এড়িয়ে যান এবং ম্যানুয়ালি পূরণ করুন',
    'eligibility.step2': 'ধাপ ২: বিবরণ পর্যালোচনা এবং সম্পাদনা করুন',
    'eligibility.use_voice': 'ভয়েস ইনপুট ব্যবহার করুন',
    'eligibility.check_btn': 'যোগ্যতা পরীক্ষা করুন',
    'eligibility.checking': 'যোগ্যতা পরীক্ষা করা হচ্ছে...',
    'form.state': 'রাজ্য',
    'form.district': 'জেলা',
    'form.land_size': 'জমির আকার (একর)',
    'form.crop_type': 'ফসলের ধরন',
    'form.category': 'শ্রেণী',
    'form.annual_income': 'বার্ষিক আয় (₹)',
    'form.income_tax_payer': 'আয়কর প্রদানকারী',
    'form.pension': 'পেনশন পাচ্ছেন',
    'form.pension_amount': 'মাসিক পেনশন পরিমাণ (₹)',
    'form.electricity': 'বিদ্যুৎ সংযোগ',
    'form.select': 'নির্বাচন করুন',
    'form.select_state': 'রাজ্য নির্বাচন করুন',
    'form.select_district': 'জেলা নির্বাচন করুন',
    'form.select_category': 'শ্রেণী নির্বাচন করুন',
    'form.yes': 'হ্যাঁ',
    'form.no': 'না',
    'form.required': 'প্রয়োজনীয়',
    'results.recommended': 'প্রস্তাবিত প্রকল্প',
    'results.best_match': 'আপনার প্রোফাইলের জন্য সেরা মিল',
    'results.eligible': 'যোগ্য',
    'results.not_eligible': 'অযোগ্য',
    'results.total_schemes': 'মোট যোগ্য প্রকল্প',
    'results.eligible_schemes': 'যোগ্য প্রকল্প',
    'results.check_another': 'অন্য যোগ্যতা পরীক্ষা করুন',
    'common.back': 'পিছনে',
    'common.next': 'পরবর্তী',
    'common.submit': 'জমা দিন',
    'common.cancel': 'বাতিল করুন',
    'common.save': 'সংরক্ষণ করুন',
    'common.edit': 'সম্পাদনা করুন',
    'common.delete': 'মুছুন',
    'common.close': 'বন্ধ করুন',
    'common.loading': 'লোড হচ্ছে...',
    'common.error': 'ত্রুটি',
    'common.success': 'সফলতা',
  },
  pa: {
    'nav.home': 'ਹੋਮ',
    'nav.features': 'ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    'nav.how_it_works': 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    'nav.about': 'ਬਾਰੇ',
    'nav.stories': 'ਕਹਾਣੀਆਂ',
    'nav.faq': 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ',
    'nav.contact': 'ਸੰਪਰਕ ਕਰੋ',
    'nav.login': 'ਲਾਗਇਨ',
    'nav.register': 'ਰਜਿਸਟਰ',
    'nav.profile': 'ਪ੍ਰੋਫਾਈਲ',
    'nav.history': 'ਇਤਿਹਾਸ',
    'nav.feedback': 'ਫੀਡਬੈਕ',
    'nav.support': 'ਸਹਾਇਤਾ',
    'nav.logout': 'ਲਾਗਆਉਟ',
    'hero.title': 'ਆਪਣੀ ਯੋਗਤਾ ਦੀ ਜਾਂਚ ਕਰੋ',
    'hero.subtitle': 'ਕਿਸੇ ਵੀ ਭਾਸ਼ਾ ਵਿੱਚ ਵੌਇਸ ਇਨਪੁੱਟ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਤੇਜ਼ੀ ਨਾਲ ਜਾਂਚ ਕਰੋ ਕਿ ਤੁਸੀਂ ਕਿਹੜੀਆਂ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਲਈ ਯੋਗ ਹੋ',
    'hero.cta': 'ਹੁਣੇ ਯੋਗਤਾ ਦੀ ਜਾਂਚ ਕਰੋ',
    'hero.quick_easy': 'ਤੇਜ਼ ਅਤੇ ਆਸਾਨ',
    'hero.multilingual': 'ਬਹੁ-ਭਾਸ਼ਾਈ ਵੌਇਸ ਸਹਾਇਤਾ',
    'eligibility.title': 'ਆਪਣੀ ਯੋਗਤਾ ਦੀ ਜਾਂਚ ਕਰੋ',
    'eligibility.subtitle': 'ਕਿਸੇ ਵੀ ਭਾਸ਼ਾ ਵਿੱਚ ਵੌਇਸ ਇਨਪੁੱਟ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਤੇਜ਼ੀ ਨਾਲ ਜਾਂਚ ਕਰੋ ਕਿ ਤੁਸੀਂ ਕਿਹੜੀਆਂ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਲਈ ਯੋਗ ਹੋ',
    'eligibility.step1': 'ਕਦਮ 1: ਵੌਇਸ ਇਨਪੁੱਟ ਵਰਤੋਂ',
    'eligibility.voice_instruction': 'ਮਾਈਕ੍ਰੋਫੋਨ ਤੇ ਕਲਿੱਕ ਕਰੋ ਅਤੇ ਕਿਸੇ ਵੀ ਭਾਸ਼ਾ ਵਿੱਚ ਆਪਣੇ ਵੇਰਵੇ ਬੋਲੋ। ਅਸੀਂ ਆਪਣੇ ਆਪ ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਦਾ ਪਤਾ ਲਗਾਵਾਂਗੇ ਅਤੇ ਫਾਰਮ ਭਰਾਂਗੇ।',
    'eligibility.input_fields': '(ਰਾਜ, ਜ਼ਿਲ੍ਹਾ, ਜ਼ਮੀਨ ਦਾ ਆਕਾਰ, ਫਸਲ ਦੀ ਕਿਸਮ, ਸ਼੍ਰੇਣੀ, ਸਾਲਾਨਾ ਆਮਦਨ, ਆਮਦਨ ਟੈਕਸ ਸਥਿਤੀ, ਪੈਨਸ਼ਨ ਸਥਿਤੀ, ਬਿਜਲੀ ਕਨੈਕਸ਼ਨ)',
    'eligibility.start_recording': 'ਰਿਕਾਰਡਿੰਗ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ',
    'eligibility.stop_recording': 'ਰਿਕਾਰਡਿੰਗ ਬੰਦ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ',
    'eligibility.processing': 'ਤੁਹਾਡੀ ਬੋਲੀ ਦੀ ਪ੍ਰਕਿਰਿਆ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...',
    'eligibility.skip_manual': 'ਛੱਡੋ ਅਤੇ ਹੱਥੀਂ ਭਰੋ',
    'eligibility.step2': 'ਕਦਮ 2: ਵੇਰਵਿਆਂ ਦੀ ਸਮੀਖਿਆ ਅਤੇ ਸੰਪਾਦਨ ਕਰੋ',
    'eligibility.use_voice': 'ਵੌਇਸ ਇਨਪੁੱਟ ਵਰਤੋਂ',
    'eligibility.check_btn': 'ਯੋਗਤਾ ਦੀ ਜਾਂਚ ਕਰੋ',
    'eligibility.checking': 'ਯੋਗਤਾ ਦੀ ਜਾਂਚ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...',
    'form.state': 'ਰਾਜ',
    'form.district': 'ਜ਼ਿਲ੍ਹਾ',
    'form.land_size': 'ਜ਼ਮੀਨ ਦਾ ਆਕਾਰ (ਏਕੜ)',
    'form.crop_type': 'ਫਸਲ ਦੀ ਕਿਸਮ',
    'form.category': 'ਸ਼੍ਰੇਣੀ',
    'form.annual_income': 'ਸਾਲਾਨਾ ਆਮਦਨ (₹)',
    'form.income_tax_payer': 'ਆਮਦਨ ਟੈਕਸ ਦਾਤਾ',
    'form.pension': 'ਪੈਨਸ਼ਨ ਪ੍ਰਾਪਤ ਕਰ ਰਹੇ ਹੋ',
    'form.pension_amount': 'ਮਾਸਿਕ ਪੈਨਸ਼ਨ ਰਕਮ (₹)',
    'form.electricity': 'ਬਿਜਲੀ ਕਨੈਕਸ਼ਨ',
    'form.select': 'ਚੁਣੋ',
    'form.select_state': 'ਰਾਜ ਚੁਣੋ',
    'form.select_district': 'ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ',
    'form.select_category': 'ਸ਼੍ਰੇਣੀ ਚੁਣੋ',
    'form.yes': 'ਹਾਂ',
    'form.no': 'ਨਹੀਂ',
    'form.required': 'ਲੋੜੀਂਦਾ',
    'results.recommended': 'ਸਿਫਾਰਸ਼ ਕੀਤੀ ਯੋਜਨਾ',
    'results.best_match': 'ਤੁਹਾਡੇ ਪ੍ਰੋਫਾਈਲ ਲਈ ਸਭ ਤੋਂ ਵਧੀਆ ਮੇਲ',
    'results.eligible': 'ਯੋਗ',
    'results.not_eligible': 'ਅਯੋਗ',
    'results.total_schemes': 'ਕੁੱਲ ਯੋਗ ਯੋਜਨਾਵਾਂ',
    'results.eligible_schemes': 'ਯੋਗ ਯੋਜਨਾਵਾਂ',
    'results.check_another': 'ਕਿਸੇ ਹੋਰ ਯੋਗਤਾ ਦੀ ਜਾਂਚ ਕਰੋ',
    'common.back': 'ਪਿੱਛੇ',
    'common.next': 'ਅੱਗੇ',
    'common.submit': 'ਜਮ੍ਹਾਂ ਕਰੋ',
    'common.cancel': 'ਰੱਦ ਕਰੋ',
    'common.save': 'ਸੁਰੱਖਿਅਤ ਕਰੋ',
    'common.edit': 'ਸੰਪਾਦਿਤ ਕਰੋ',
    'common.delete': 'ਮਿਟਾਓ',
    'common.close': 'ਬੰਦ ਕਰੋ',
    'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'common.error': 'ਗਲਤੀ',
    'common.success': 'ਸਫਲਤਾ',
  },
  or: {
    'nav.home': 'ହୋମ୍',
    'nav.features': 'ବୈଶିଷ୍ଟ୍ୟଗୁଡିକ',
    'nav.how_it_works': 'ଏହା କିପରି କାମ କରେ',
    'nav.about': 'ବିଷୟରେ',
    'nav.stories': 'କାହାଣୀ',
    'nav.faq': 'ବାରମ୍ବାର ପଚରାଯାଉଥିବା ପ୍ରଶ୍ନ',
    'nav.contact': 'ଯୋଗାଯୋଗ',
    'nav.login': 'ଲଗଇନ୍',
    'nav.register': 'ରେଜିଷ୍ଟର',
    'nav.profile': 'ପ୍ରୋଫାଇଲ୍',
    'nav.history': 'ଇତିହାସ',
    'nav.feedback': 'ମତାମତ',
    'nav.support': 'ସହାୟତା',
    'nav.logout': 'ଲଗଆଉଟ୍',
    'hero.title': 'ଆପଣଙ୍କର ଯୋଗ୍ୟତା ଯାଞ୍ଚ କରନ୍ତୁ',
    'hero.subtitle': 'ଯେକୌଣସି ଭାଷାରେ ଭଏସ୍ ଇନପୁଟ୍ ବ୍ୟବହାର କରି ଶୀଘ୍ର ଯାଞ୍ଚ କରନ୍ତୁ ଆପଣ କେଉଁ ସରକାରୀ ଯୋଜନା ପାଇଁ ଯୋଗ୍ୟ',
    'hero.cta': 'ବର୍ତ୍ତମାନ ଯୋଗ୍ୟତା ଯାଞ୍ଚ କରନ୍ତୁ',
    'hero.quick_easy': 'ଶୀଘ୍ର ଏବଂ ସହଜ',
    'hero.multilingual': 'ବହୁଭାଷୀ ଭଏସ୍ ସମର୍ଥନ',
    'eligibility.title': 'ଆପଣଙ୍କର ଯୋଗ୍ୟତା ଯାଞ୍ଚ କରନ୍ତୁ',
    'eligibility.subtitle': 'ଯେକୌଣସି ଭାଷାରେ ଭଏସ୍ ଇନପୁଟ୍ ବ୍ୟବହାର କରି ଶୀଘ୍ର ଯାଞ୍ଚ କରନ୍ତୁ ଆପଣ କେଉଁ ସରକାରୀ ଯୋଜନା ପାଇଁ ଯୋଗ୍ୟ',
    'eligibility.step1': 'ପଦକ୍ଷେପ 1: ଭଏସ୍ ଇନପୁଟ୍ ବ୍ୟବହାର କରନ୍ତୁ',
    'eligibility.voice_instruction': 'ମାଇକ୍ରୋଫୋନ୍ କ୍ଲିକ୍ କରନ୍ତୁ ଏବଂ ଯେକୌଣସି ଭାଷାରେ ଆପଣଙ୍କର ବିବରଣୀ କୁହନ୍ତୁ। ଆମେ ସ୍ୱୟଂଚାଳିତ ଭାବରେ ଆପଣଙ୍କର ଭାଷା ଚିହ୍ନଟ କରିବୁ ଏବଂ ଫର୍ମ ପୂରଣ କରିବୁ।',
    'eligibility.input_fields': '(ରାଜ୍ୟ, ଜିଲ୍ଲା, ଜମି ଆକାର, ଫସଲ ପ୍ରକାର, ବର୍ଗ, ବାର୍ଷିକ ଆୟ, ଆୟକର ସ୍ଥିତି, ପେନସନ୍ ସ୍ଥିତି, ବିଦ୍ୟୁତ୍ ସଂଯୋଗ)',
    'eligibility.start_recording': 'ରେକର୍ଡିଂ ଆରମ୍ଭ କରିବାକୁ କ୍ଲିକ୍ କରନ୍ତୁ',
    'eligibility.stop_recording': 'ରେକର୍ଡିଂ ବନ୍ଦ କରିବାକୁ କ୍ଲିକ୍ କରନ୍ତୁ',
    'eligibility.processing': 'ଆପଣଙ୍କର ବକ୍ତବ୍ୟ ପ୍ରକ୍ରିୟାକରଣ କରାଯାଉଛି...',
    'eligibility.skip_manual': 'ଛାଡି ହସ୍ତକୃତ ଭାବରେ ପୂରଣ କରନ୍ତୁ',
    'eligibility.step2': 'ପଦକ୍ଷେପ 2: ବିବରଣୀ ସମୀକ୍ଷା ଏବଂ ସମ୍ପାଦନା କରନ୍ତୁ',
    'eligibility.use_voice': 'ଭଏସ୍ ଇନପୁଟ୍ ବ୍ୟବହାର କରନ୍ତୁ',
    'eligibility.check_btn': 'ଯୋଗ୍ୟତା ଯାଞ୍ଚ କରନ୍ତୁ',
    'eligibility.checking': 'ଯୋଗ୍ୟତା ଯାଞ୍ଚ କରାଯାଉଛି...',
    'form.state': 'ରାଜ୍ୟ',
    'form.district': 'ଜିଲ୍ଲା',
    'form.land_size': 'ଜମି ଆକାର (ଏକର)',
    'form.crop_type': 'ଫସଲ ପ୍ରକାର',
    'form.category': 'ବର୍ଗ',
    'form.annual_income': 'ବାର୍ଷିକ ଆୟ (₹)',
    'form.income_tax_payer': 'ଆୟକର ଦାତା',
    'form.pension': 'ପେନସନ୍ ପାଉଛନ୍ତି',
    'form.pension_amount': 'ମାସିକ ପେନସନ୍ ପରିମାଣ (₹)',
    'form.electricity': 'ବିଦ୍ୟୁତ୍ ସଂଯୋଗ',
    'form.select': 'ଚୟନ କରନ୍ତୁ',
    'form.select_state': 'ରାଜ୍ୟ ଚୟନ କରନ୍ତୁ',
    'form.select_district': 'ଜିଲ୍ଲା ଚୟନ କରନ୍ତୁ',
    'form.select_category': 'ବର୍ଗ ଚୟନ କରନ୍ତୁ',
    'form.yes': 'ହଁ',
    'form.no': 'ନା',
    'form.required': 'ଆବଶ୍ୟକ',
    'results.recommended': 'ସୁପାରିଶ କରାଯାଇଥିବା ଯୋଜନା',
    'results.best_match': 'ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ପାଇଁ ସର୍ବୋତ୍ତମ ମେଳ',
    'results.eligible': 'ଯୋଗ୍ୟ',
    'results.not_eligible': 'ଅଯୋଗ୍ୟ',
    'results.total_schemes': 'ମୋଟ ଯୋଗ୍ୟ ଯୋଜନା',
    'results.eligible_schemes': 'ଯୋଗ୍ୟ ଯୋଜନା',
    'results.check_another': 'ଅନ୍ୟ ଯୋଗ୍ୟତା ଯାଞ୍ଚ କରନ୍ତୁ',
    'common.back': 'ପଛକୁ',
    'common.next': 'ପରବର୍ତ୍ତୀ',
    'common.submit': 'ଦାଖଲ କରନ୍ତୁ',
    'common.cancel': 'ବାତିଲ୍ କରନ୍ତୁ',
    'common.save': 'ସଂରକ୍ଷଣ କରନ୍ତୁ',
    'common.edit': 'ସମ୍ପାଦନା କରନ୍ତୁ',
    'common.delete': 'ବିଲୋପ କରନ୍ତୁ',
    'common.close': 'ବନ୍ଦ କରନ୍ତୁ',
    'common.loading': 'ଲୋଡ୍ ହେଉଛି...',
    'common.error': 'ତ୍ରୁଟି',
    'common.success': 'ସଫଳତା',
  },
};
